/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'rule-editor-advanced': RouteRecordInfo<'rule-editor-advanced', '/rule-editor-advanced', Record<never, never>, Record<never, never>>,
    'rule-editor-custom': RouteRecordInfo<'rule-editor-custom', '/rule-editor-custom', Record<never, never>, Record<never, never>>,
    'rule-editor-dynamic': RouteRecordInfo<'rule-editor-dynamic', '/rule-editor-dynamic', Record<never, never>, Record<never, never>>,
    'rule-editor-sample': RouteRecordInfo<'rule-editor-sample', '/rule-editor-sample', Record<never, never>, Record<never, never>>,
    'rule-editor-simulator': RouteRecordInfo<'rule-editor-simulator', '/rule-editor-simulator', Record<never, never>, Record<never, never>>,
    'second-page': RouteRecordInfo<'second-page', '/second-page', Record<never, never>, Record<never, never>>,
  }
}
